// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace PartnerCenterPayoutAPISampleCode
{
    using System.Net.Http;
    using System.Net.Http.Headers;

    /// <summary>
    /// Contains actions or methods that can be performed related to Partner Center Payout - Payments.
    /// </summary>
    public class Payments
    {
        private static HttpClient _httpClient = new HttpClient();
        private static string domain = "https://api.partner.microsoft-int.com/";
        private static string basePath = "v1.0/beta/payout";
        private static string resource = "/payments";

        /// <summary>
        /// Creates a new Partner Center Payout Payments request.
        /// </summary>
        /// <param name="accessToken">AAD token generated by the UserCredentialTokenGenerator</param>
        /// <returns>Standard Http Response from the API</returns>
        public static HttpResponseMessage CreateRequest(string accessToken)
        {
            string createPaymentsRequestURI = domain + basePath + resource + "?$filter=programName eq 'Azure Marketplace'";

            HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Post, createPaymentsRequestURI);
            requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            HttpResponseMessage response = _httpClient.SendAsync(requestMessage).Result;

            return response;
        }

        /// <summary>
        /// Gets the status of an existing Partner Center Payout Payments request.
        /// </summary>
        /// <param name="accessToken">AAD token generated by the UserCredentialTokenGenerator</param>
        /// <returns>Standard Http Response from the API</returns>
        public static HttpResponseMessage GetRequest(string accessToken, string paymentsStatusUrl)
        {
            //paymentsStatusUrl = domain + basePath + resource + "/d0c8649b-1519-4815-a1d9-4c09b01ee599";

            HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Get, paymentsStatusUrl);
            requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            HttpResponseMessage response = _httpClient.SendAsync(requestMessage).Result;

            return response;
        }

        /// <summary>
        /// Deletes an existing Partner Center Payout Payments request.
        /// </summary>
        /// <param name="accessToken">AAD token generated by the UserCredentialTokenGenerator</param>
        /// <returns>Standard Http Response from the API</returns>
        public static HttpResponseMessage DeleteRequest(string accessToken)
        {
            string deletePaymentsRequestURI = domain + basePath + resource + "/2a183ea4-ee0c-4fe6-a685-ce48790894ff";

            HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Delete, deletePaymentsRequestURI);
            requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            HttpResponseMessage response = _httpClient.SendAsync(requestMessage).Result;

            return response;
        }
    }
}